### ISSUE TITLE
Question about setup

### ISSUE THREAD

**Issue by ntopulos** [GlueDev/laravel-stackdriver#5]
Hi,

Some help would be greatly appreciated to get this package to work.

1. **Credentials**

   > At the time of writing, Google prefers you to authenticate using a service account. **It** will throw a warning otherwise, which you can (but probably should not) disable by setting SUPPRESS_GCLOUD_CREDS_WARNING=true

   What is "it"? Where will any warning be thrown? In the local logs? On Google Console?

2. **Service account**

   > Create a service account with the **appropriate roles** attached to it and add it to your project. Make sure not to commit this file to git, because of security. You can then specify the path to the service account JSON file in the keyFilePath or in the STACKDRIVER_KEY_FILE_PATH environment variable.

   What are the appropriate roles for each functionality of this package?
 
   I tried adding these 3 to get logging on Google:
   - Cloud Trace Admin
   - Logging Admin
   - Error Reporting User

3. **Log channel**

   The plugin has a separate configuration where we can enable and disable the Stack Drive logging, but how does it integrate with the Laravel logging channel?  
   Our app being doesn't have write permission, therefore we would like to use Stack Driver as the only logging channel. Is it possible? Is enabling Stack Driver supposed to disable other logging channels?

4. **How to make it work?**

   After installing the package, and adding a configuration nothing happens:

        STACKDRIVER_ENABLED=true
        STACKDRIVER_LOGGING_ENABLED=true
        STACKDRIVER_TRACING_ENABLED=false
        STACKDRIVER_ERROR_REPORTING_ENABLED=true
        STACKDRIVER_KEY_FILE_PATH=storage/keyfile.json

   Nothing appears in the Google Cloud Console, current logging channel is still used, and no error related to this package appears in there. When the key file path is wrong, there are no errors either.

**Comment by DiederikvandenB** [comment]
1. See: https://github.com/googleapis/google-auth-library-php/blob/cccae18e0ef9d156e0971087a2580f0e3c232896/src/Credentials/UserRefreshCredentials.php#L89

2. Required roles is dependent on your setup/environment. Google lists the available roles on these pages:
- https://cloud.google.com/error-reporting/docs/iam
- https://cloud.google.com/trace/docs/iam
- https://cloud.google.com/logging/docs/access-control

3. Right now, our logging system doesn't integrate with Laravel's default logging system. Potentially we could change this, but I currently don't have much time to look at that. Maybe you could shoot in a PR if you're interested in looking at this. Otherwise, in your case, it should be possible/suffice to just disable the default Laravel logger.

4. This seems like a weird issue. Potentially environmentally related. Having said that, I personally have not used this repo in a while. I'll quickly check it out and see if I can still get it to work.

**Comment by DiederikvandenB** [comment]
So I had a look, and I can still get everything to work. Some pointers if you don't see anything appear in GCP:

- Disable the batching features (for instance, by default, logs are sent in batches of 50)
- Select the correct resources when looking for logs/traces in GCP
- I made a service account with the following three roles:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/6132723/68124077-bc94bc80-ff0e-11e9-9b25-19aac2c31ead.png">

- And added this to my `.env`:
```
STACKDRIVER_ENABLED=true
STACKDRIVER_LOGGING_ENABLED=true
STACKDRIVER_TRACING_ENABLED=true
STACKDRIVER_ERROR_REPORTING=true
STACKDRIVER_PROJECT_ID=my-project-256216
STACKDRIVER_KEY_FILE_PATH=/tmp/stackdriver/storage/key.json
```

Since everything seems to work fine, I will close this issue. Feel free to reach out if you keep encountering issues.

**Comment by ntopulos** [comment]
Thank you for checking on your side. I followed your instructions, it still doesn't work, but at least the package is loaded and reacts to configuration changes.  
The problem was the cache of composer and Laravel. After clearing them, I now get errors when the keyfile does not exist:

    composer dump-autoload
    php artisan config:clear

But there is still nothing on the Google Console.

Maybe I do not understand how this plugin is supposed to work. 
My controller has a log command and I expect to see this log message on Stackdriver :

    \Log::debug('New log entry!');

This is my `.env`:

    STACKDRIVER_ENABLED=true
    STACKDRIVER_LOGGING_ENABLED=true
    STACKDRIVER_TRACING_ENABLED=false
    STACKDRIVER_ERROR_REPORTING=true
    STACKDRIVER_PROJECT_ID=my-project-name
    STACKDRIVER_KEY_FILE_PATH=../storage/key.json

The readme doesn't say anything about that, but I also tried replacing `stack` config by:

    LOG_CHANNEL=stackdriver

> Disable the batching features (for instance, by default, logs are sent in batches of 50)

I suppose it is irrelevant if I did not set up the batch daemon?

**Comment by DiederikvandenB** [comment]
I think the readme can/should be more clear about the batch daemon. Regardless of whether you have it running, everything is send to Google's APIs in batches. The [Google Stackdriver](https://cloud.google.com/logging/docs/setup/php) docs explains why:

> The PSR-3 logger sends the logs synchronously. This means that whenever you emit a log, it will add RPC latency to the user request. Especially if you emit multiple logs in a single request, the added latency will be significant. You probably want to avoid that.

Hence, I decided to set `batchEnabled` to `true` by default (check your `stackdriver.php` config).

Now, about the daemon, I tried looking for detailed docs on why this is recommended/what it does exactly, but I couldn't find anything right now. Maybe have a look at this directory:
https://github.com/googleapis/google-cloud-php/tree/master/Core/src/Batch

What I remember from implementing this a while back is that despite the batching, once every X requests would still be delayed due to the traffic to and from the google servers. This is where the daemon comes in. I think it takes care of the batching and talking to Google, allowing your application to run without delays.

Finally, I advise you to look at how the logger client is set up:
https://github.com/GlueDev/laravel-stackdriver/blob/develop/src/Stackdriver.php#L39-L51

Then, check out Google's docs:
https://googleapis.github.io/google-cloud-php/#/docs/google-cloud/v0.118.0/logging/psrlogger

I should make this more clear in the docs of this package, and I will do so when I find the time for that :).
