### ISSUE TITLE
bug: opencensus.so: undefined symbol: ZVAL_DESTRUCTOR

### ISSUE THREAD

**Issue by ibrunotome** [GlueDev/laravel-stackdriver#6]
symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20180731/opencensus.so: undefined symbol: ZVAL_DESTRUCTOR

Seems to have been resolved in dev-master (https://github.com/census-instrumentation/opencensus-php/issues/235#issuecomment-576568564)

Could you please update it in the package dependencies?

**Comment by DiederikvandenB** [comment]
Hi, thank you for pointing this issue out.

I think that changing the dependency to `dev-master` might lead to problems for projects which have `minimum-stability` set to `stable`, in which case I am not a huge fan of that.

A temporary solution would be to change the dependency in this repo, but not releasing a new version to composer (yet). You can then select `dev-master` for this package, until OpenCensus (finally) release a new version. Would you be okay with that?

I’m on mobile now, so can’t push the change. I will have time tomorrow though.

**Comment by ibrunotome** [comment]
I'm ok with that if isn't a problem to you, thank you for your attention.

**Comment by DiederikvandenB** [comment]
It seemed like requiring `dev-master` for `opencensus/opencensus` lead to dependency errors for [opencensus-php-exporter-stackdriver](https://github.com/census-ecosystem/opencensus-php-exporter-stackdriver/blob/master/composer.json), as this has its `minimum-stability` set to `stable` and it also requires `opencensus/opencensus`.

In order to still resolve the issue, I think it's best to use a inline alias ([more info](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias)) in your `composer.json`. This works for me:

    "require": {
        "gluedev/laravel-stackdriver": "^0.1.2",
        "opencensus/opencensus": "dev-master as 0.5.2"
    },

I will keep this issue open until a new OpenCensus version is released. I started an issue for that [here](https://github.com/census-instrumentation/opencensus-php/issues/253).

**Comment by ibrunotome** [comment]
Just a feedback, even with dev-master the `/usr/local/lib/php/extensions/no-debug-non-zts-20180731/opencensus.so: undefined symbol: ZVAL_DESTRUCTOR` persists 😞

**Comment by ibrunotome** [comment]
Ok, I got it, here's what I did:

1. Created an opencensus folder in the root of my project.
2. Copied https://github.com/census-instrumentation/opencensus-php/tree/master/ext content to it.
3. Deleted docker and tests folder that was come in step 2.
4. Installed opencensus from source code:

```Dockerfile
COPY opencensus/* /tmp/opencensus/

RUN cd /tmp/opencensus \
    && phpize \
    && ./configure --enable-opencensus \
    && make -j "$(nproc)" \
    && make install \
    && cd ~ \
    && rm -r /tmp/opencensus \
    && docker-php-ext-enable opencensus
```

And it's working now.

**Comment by DiederikvandenB** [comment]
Glad it is working for you now!

**Comment by rediphone** [comment]
I am also having this problem, I am attempting to use @ibrunotom's suggested solution. 
I am not using laravel-stackdriver though, just opencensus-php and getting the same error he has described.... so could be completely barking up the wrong tree here

there are other threads with this issue. I cant find a solution so just trying some stuff.. :(
